apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: hello-app
        image: us-west1-docker.pkg.dev/qwiklabs-gcp-02-4aee9e6518ba/my-repository/hello-cloudbuild-dev:v1.0

