apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: production-app
  template:
    metadata:
      labels:
        app: production-app
    spec:
       containers:
       - name: hello-cloudbuild
       image: us-west1-docker.pkg.dev/qwiklabs-gcp-03-9045b764c192/my-repository/hello-cloudbuild:v1.0
       ports:
       - containerPort: 8080

